-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GeoData/sql/abstractSchemaChanges/patch-postgres-externally-backed.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  geo_tags ALTER gt_primary TYPE SMALLINT;
ALTER TABLE  geo_tags ALTER gt_primary
DROP  DEFAULT;
ALTER TABLE  geo_tags ALTER gt_name TYPE TEXT;
ALTER TABLE  geo_tags ALTER gt_name
DROP  DEFAULT;