-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../mediawiki-extensions-GeoData/sql/abstract/geo_tags.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/geo_tags (
  gt_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  gt_page_id INTEGER UNSIGNED NOT NULL,
  gt_globe VARCHAR(32) NOT NULL,
  gt_primary BOOLEAN NOT NULL,
  gt_lat NUMERIC(11, 8) NOT NULL,
  gt_lon NUMERIC(11, 8) NOT NULL,
  gt_dim INTEGER DEFAULT NULL,
  gt_type VARCHAR(32) DEFAULT NULL,
  gt_name VARCHAR(255) DEFAULT NULL,
  gt_country CHAR(2) DEFAULT NULL,
  gt_region VARCHAR(3) DEFAULT NULL
);

CREATE INDEX gt_page_primary ON /*_*/geo_tags (gt_page_id, gt_primary);

CREATE INDEX gt_page_id_id ON /*_*/geo_tags (gt_page_id, gt_id);
