-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: ../mediawiki-extensions-GeoData/sql/abstractSchemaChanges/patch-db-backend.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX gt_page_id_id ON  /*_*/geo_tags;
ALTER TABLE  /*_*/geo_tags
ADD  gt_lat_int SMALLINT NOT NULL,
ADD  gt_lon_int SMALLINT NOT NULL;
CREATE INDEX gt_spatial ON  /*_*/geo_tags (    gt_lat_int, gt_lon_int, gt_lon, gt_primary  );
CREATE INDEX gt_page_id_id ON  /*_*/geo_tags (gt_page_id);