-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GeoData/sql/abstractSchemaChanges/patch-postgres-db-backed.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/geo_tags
CHANGE  gt_primary gt_primary TINYINT(1) NOT NULL,
CHANGE  gt_name gt_name VARBINARY(255) DEFAULT NULL;